#!/bin/bash
find . -type f -name "*.gif" -printf "%f\n" | rev | cut -d. -f2- | rev | paste - <(find . -type f -name "*.gif" -printf "%f\n" | rev | cut -d. -f2- | rev | tr '[:upper:]' '[:lower:]') | sort -k2 | cut -f1

