#!/usr/bin/env bash
#This is file 9.
while IFS=":" read -r username password userid groupid userinfo home shell
do
    echo "The user $username is part of the $groupid gang, lives in $home and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $userinfo"
done < /etc/passwd
