#!/usr/bin/env bash
# This is a comment
awk 'NF >= 9 && $9 ~ /^[0-9]+$/ && $1 ~ /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ {count[$1" "$9]++} 
     END {for (key in count) print count[key], key}' access.log | sort -nr
