#!/usr/bin/env bash
# This is file 6.
hour=0

while [ $hour -le 12 ]
do
    minute=1
    while [ $minute -le 59 ]
    do
        printf "%02d:%02d\n" $hour $minute
        ((minute++))
    done
    ((hour++))
done

