#!/usr/bin/env bash
#This is a comment
# shellcheck disable=SC2009

pid=$(ps -ef | grep "[7]-highlander" | awk '{print $2}' | head -n1)

if [ -n "$pid" ]; then
    kill "$pid"
else
    echo "Process 7-highlander not found."
fi
